[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pxalyze"
version = "0.2.0"
authors = [{ name = "Ilia Moiseev", email = "ilia.moiseev.5@yandex.ru" }]
license = { text = "Apache License, Version 2.0" }
description = "Pxalyze - a single file for debugging your images"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = ["numpy"]

[project.optional-dependencies]
opencv = ["opencv-python"]

[tool.setuptools]
packages = ["pxalyze"]
package-dir = { "" = "." }

[dependency-groups]
dev = [
    "opencv-python>=4.11.0.86",
    "pytest>=7.4.4",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
